### ISSUE TITLE
Project Specification

### ISSUE THREAD

**Issue by tiagomenegaz** [tmmgarcia/http-call#1]
Tasks

- [x] create gem structure #2
- [X] add base request class #3 
- [x] add get #4
- [x] add httparty [HTTParty](https://github.com/jnunemaker/httparty/) #5
- [x] refactor get using [HTTParty](https://github.com/jnunemaker/httparty/) #6
- [x] add post #7
- [x] add retry module #3 
- [ ] update readme with installing instructions
- [ ] add put/patch
- [ ] publish to [Ruby Gems](https://guides.rubygems.org/make-your-own-gem/)
